#!/usr/bin/env node
/**
 * VowOS token pipeline.
 *
 * Masterplan section 4 requires that a token change happen in exactly one place,
 * and that any change carry a contrast check. This script is that requirement,
 * executable:
 *
 *   1. tokens.json  ->  prototype/styles/tokens.css   (generated, never hand-edited)
 *   2. every pair in contrastRequirements is measured against WCAG 2.x
 *   3. the measurements are written to docs/contrast-report.md
 *   4. a failing required pair exits non-zero, so it can block a build
 *
 * Run `node design-system/build.mjs --check` in CI: it regenerates in memory and
 * fails if the committed output has drifted from tokens.json, which is how a
 * hand-typed hex value gets caught before it forks the system.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const TOKENS = join(ROOT, 'design-system', 'tokens.json');
const CSS_OUT = join(ROOT, 'prototype', 'styles', 'tokens.css');
const REPORT_OUT = join(ROOT, 'docs', 'contrast-report.md');

const checkOnly = process.argv.includes('--check');
const tokens = JSON.parse(readFileSync(TOKENS, 'utf8'));

/* ---------------------------------------------------------------- contrast */

function parseHex(hex) {
  const raw = hex.replace('#', '');
  const full = raw.length === 3 ? [...raw].map((c) => c + c).join('') : raw;
  return {
    r: parseInt(full.slice(0, 2), 16),
    g: parseInt(full.slice(2, 4), 16),
    b: parseInt(full.slice(4, 6), 16),
  };
}

// WCAG 2.x relative luminance. https://www.w3.org/WAI/GL/wiki/Relative_luminance
function luminance(hex) {
  const { r, g, b } = parseHex(hex);
  const channel = (v) => {
    const c = v / 255;
    return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
  };
  return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b);
}

function contrastRatio(fgHex, bgHex) {
  const a = luminance(fgHex);
  const b = luminance(bgHex);
  const [hi, lo] = a > b ? [a, b] : [b, a];
  return (hi + 0.05) / (lo + 0.05);
}

function auditContrast() {
  return tokens.contrastRequirements.map((req) => {
    const fg = tokens.color[req.fg];
    const bg = tokens.color[req.bg];
    if (!fg || !bg) throw new Error(`${req.id}: unknown color token ${req.fg} or ${req.bg}`);
    const ratio = contrastRatio(fg.value, bg.value);
    const meets = ratio >= req.min;
    const expectedPass = req.expect !== 'fail';
    return { ...req, fgHex: fg.value, bgHex: bg.value, ratio, meets, ok: meets === expectedPass };
  });
}

/* --------------------------------------------------------------- css emit */

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

const GROUPS = [
  ['color', 'Color'],
  ['space', 'Spacing scale'],
  ['radius', 'Corner radius'],
  ['font', 'Type families'],
  ['fontSize', 'Type scale'],
  ['lineHeight', 'Line height'],
  ['letterSpacing', 'Letter spacing'],
  ['motion', 'Motion'],
  ['shadow', 'Elevation'],
  ['layout', 'Layout'],
];

function emitCss() {
  const lines = [
    '/*',
    ' * VowOS design tokens.',
    ' *',
    ' * GENERATED FILE - DO NOT EDIT.',
    ' * Source of truth: design-system/tokens.json',
    ' * Regenerate with: npm run tokens',
    ` * Token set version: ${tokens.$meta.version}`,
    ' */',
    '',
    ':root {',
  ];

  for (const [group, title] of GROUPS) {
    lines.push(`  /* ${title} */`);
    for (const [name, token] of Object.entries(tokens[group])) {
      const varName = `--vow-${kebab(group)}-${kebab(name)}`;
      lines.push(`  ${varName}: ${token.value};`);
    }
    lines.push('');
  }

  lines.push('  /* Derived: reduced-motion safe duration, overridden in app.css */');
  lines.push('  --vow-motion-scale: 1;');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

/* ------------------------------------------------------------ report emit */

function emitReport(results) {
  const stamp = new Date().toISOString().slice(0, 10);
  const required = results.filter((r) => r.expect !== 'fail');
  const banned = results.filter((r) => r.expect === 'fail');
  const failures = results.filter((r) => !r.ok);

  const row = (r) =>
    `| ${r.id} | \`${r.fg}\` ${r.fgHex} | \`${r.bg}\` ${r.bgHex} | ${r.ratio.toFixed(2)}:1 | ${r.min.toFixed(1)}:1 | ${r.ok ? 'Pass' : 'FAIL'} | ${r.context} |`;

  return `# Contrast report

Generated by \`design-system/build.mjs\` from \`design-system/tokens.json\`. Do not edit by hand.

**Token set version:** ${tokens.$meta.version}
**Generated:** ${stamp}
**Result:** ${failures.length === 0 ? 'All checks pass.' : `${failures.length} check(s) failed.`}

Ratios are WCAG 2.x contrast ratios. The 4.5:1 threshold is the AA minimum for body text and the 3:1 threshold is the AA minimum for large text, per W3C Understanding Contrast Minimum.

## Required pairs

| ID | Foreground | Background | Measured | Required | Result | Context |
|---|---|---|---:|---:|---|---|
${required.map(row).join('\n')}

## Pairs that must fail

These document bans rather than allowances. UI Plan section 13 forbids rose clay, mist blue, and soft gold as text colors on a light surface. The build asserts they *cannot* pass, so the ban stays true if a value is ever adjusted.

| ID | Foreground | Background | Measured | Would need | Result | Context |
|---|---|---|---:|---:|---|---|
${banned.map(row).join('\n')}

## Standing findings

**CF-01 — Terracotta is a fill, not a text color.**
Terracotta measures ${contrastRatio(tokens.color.terracotta.value, tokens.color.porcelain.value).toFixed(2)}:1 on porcelain and ${contrastRatio(tokens.color.terracotta.value, tokens.color.paper.value).toFixed(2)}:1 on paper. The second value is below the 4.5:1 body-text minimum. Terracotta is therefore cleared only as a button fill, a left rule, and large-text emphasis at 24px or above. Small text that needs a warm accent uses ink or moss. This is enforced in \`app.css\` by never assigning terracotta to a body-copy class.

**CF-02 — Porcelain and paper are close by design, so layering never relies on fill alone.**
The two surfaces differ by ${(contrastRatio(tokens.color.porcelain.value, tokens.color.paper.value)).toFixed(2)}:1, which is intentional warmth but, as UI Plan 3.1 warns, can collapse on a low-quality panel in daylight. Every paper surface in the system therefore carries a hairline border in addition to its fill. Removing that border is a system change, not a visual preference.
`;
}

/* -------------------------------------------------------------------- run */

const css = emitCss();
const results = auditContrast();
const report = emitReport(results);
const failures = results.filter((r) => !r.ok);

if (checkOnly) {
  const problems = [];
  for (const [path, expected] of [[CSS_OUT, css], [REPORT_OUT, report]]) {
    let actual = '';
    try {
      actual = readFileSync(path, 'utf8');
    } catch {
      problems.push(`${path} is missing`);
      continue;
    }
    // The report carries a generation date, so compare everything but that line.
    const strip = (s) => s.split('\n').filter((l) => !l.startsWith('**Generated:**')).join('\n');
    if (strip(actual) !== strip(expected)) problems.push(`${path} has drifted from tokens.json`);
  }
  for (const p of problems) console.error(`  drift: ${p}`);
  if (problems.length) {
    console.error('\nToken drift detected. Run `npm run tokens` and commit the result.');
    process.exit(1);
  }
  console.log('Tokens in sync.');
} else {
  writeFileSync(CSS_OUT, css);
  writeFileSync(REPORT_OUT, report);
  console.log(`  wrote ${CSS_OUT.replace(ROOT + '/', '')}`);
  console.log(`  wrote ${REPORT_OUT.replace(ROOT + '/', '')}`);
}

for (const r of results) {
  if (!r.ok) {
    const wanted = r.expect === 'fail' ? `must NOT reach ${r.min}:1` : `needs ${r.min}:1`;
    console.error(`  contrast ${r.id}: ${r.fg} on ${r.bg} measured ${r.ratio.toFixed(2)}:1, ${wanted}`);
  }
}

console.log(
  `Contrast: ${results.length - failures.length}/${results.length} checks pass.`
);

if (failures.length) {
  console.error('Contrast requirements not met. This blocks the build by design (Masterplan section 4).');
  process.exit(1);
}
